CREATE TABLE TB_CONFIG (
  ID        INTEGER PRIMARY KEY   AUTO_INCREMENT,
  PROJECT   VARCHAR(255) NOT NULL,
  PROFILE   VARCHAR(255) NOT NULL DEFAULT 'default',
  `KEY`     VARCHAR(255) NOT NULL,
  `VALUE`   VARCHAR(255) NOT NULL,
  CREATE_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX TB_CONFIG_UNIQ ON TB_CONFIG (PROJECT, PROFILE, `KEY`);

INSERT INTO TB_CONFIG (PROJECT, `PROFILE`, `KEY`, `VALUE`) VALUE ('demo', 'prod', 'sample.key', 'sample.value');
